// Built-in SRE runbook definitions.
// These ship with SREAI and cannot be deleted (only custom runbooks can).

export const BUILTIN_RUNBOOKS = [
  {
    id: 'rb-disk-recovery',
    name: 'Disk Space Recovery',
    description: 'Identify and recover disk space on a Linux server. Finds the largest files and directories, cleans temp files, and checks log rotation.',
    category: 'storage',
    severity: 'critical',
    builtin: true,
    platforms: ['linux', 'darwin'],
    tags: ['disk', 'storage', 'cleanup', 'capacity'],
    estimatedMinutes: 8,
    steps: [
      { order: 1, title: 'Check disk usage', command: 'df -h', description: 'See which filesystems are full or nearly full.', risk: 'safe' },
      { order: 2, title: 'Find largest directories', command: 'sudo du -xh / 2>/dev/null | sort -rh | head -20', description: 'Identify the top 20 space consumers.', risk: 'safe' },
      { order: 3, title: 'Check /tmp size', command: 'du -sh /tmp 2>/dev/null && ls -la /tmp/ | head -20', description: 'Temporary files can accumulate. Review before cleaning.', risk: 'safe' },
      { order: 4, title: 'Find old log files', command: 'find /var/log -type f -name "*.gz" -mtime +30 2>/dev/null | head -20', description: 'Compressed logs older than 30 days are usually safe to remove.', risk: 'safe' },
      { order: 5, title: 'Check journal disk usage', command: 'journalctl --disk-usage 2>/dev/null', description: 'Systemd journal can grow very large if not rotated.', risk: 'safe' },
      { order: 6, title: 'Clean package cache', command: 'apt-get clean 2>/dev/null || yum clean all 2>/dev/null; echo "Package cache cleaned"', description: 'Remove cached package downloads.', risk: 'caution' },
    ],
  },
  {
    id: 'rb-memory-diag',
    name: 'Memory Diagnostics',
    description: 'Investigate high memory usage. Shows memory breakdown, swap usage, and identifies the heaviest processes.',
    category: 'compute',
    severity: 'warning',
    builtin: true,
    platforms: ['linux', 'darwin'],
    tags: ['memory', 'oom', 'ram', 'swap'],
    estimatedMinutes: 5,
    steps: [
      { order: 1, title: 'Memory overview', command: 'free -mh', description: 'Total, used, free, and available memory with human-readable sizes.', risk: 'safe' },
      { order: 2, title: 'Top memory consumers', command: 'ps aux --sort=-%mem | head -15', description: 'Processes sorted by memory usage (descending).', risk: 'safe' },
      { order: 3, title: 'Virtual memory stats', command: 'vmstat 1 5', description: 'Live memory, swap, and I/O stats over 5 seconds.', risk: 'safe' },
      { order: 4, title: 'OOM killer history', command: 'sudo dmesg -T 2>/dev/null | grep -i "killed process" | tail -10', description: 'Check if the OOM killer has been active recently.', risk: 'safe' },
      { order: 5, title: 'Swap usage by process', command: 'for f in /proc/[0-9]*/status; do awk \'/^(Name|VmSwap)/{printf "%s ", $2}\' "$f" 2>/dev/null && echo; done | sort -k2 -rn | head -10', description: 'Which processes are swapping the most.', risk: 'safe' },
    ],
  },
  {
    id: 'rb-cpu-diag',
    name: 'CPU Diagnostics',
    description: 'Investigate high CPU usage. Identifies hot processes, checks load averages, and looks for runaway loops.',
    category: 'compute',
    severity: 'warning',
    builtin: true,
    platforms: ['linux', 'darwin'],
    tags: ['cpu', 'load', 'performance'],
    estimatedMinutes: 5,
    steps: [
      { order: 1, title: 'Load averages', command: 'uptime', description: 'Check 1/5/15 minute load averages.', risk: 'safe' },
      { order: 2, title: 'Top CPU consumers', command: 'ps aux --sort=-%cpu | head -15', description: 'Processes consuming the most CPU right now.', risk: 'safe' },
      { order: 3, title: 'CPU per core', command: 'mpstat -P ALL 1 3 2>/dev/null || top -bn1 | head -5', description: 'Per-core utilization to spot single-threaded bottlenecks.', risk: 'safe' },
      { order: 4, title: 'Recent CPU-heavy processes', command: 'sudo journalctl -p warning -n 30 --no-pager 2>/dev/null | grep -i "cpu\\|load\\|throttl" | tail -10', description: 'Journal entries related to CPU pressure.', risk: 'safe' },
    ],
  },
  {
    id: 'rb-service-health',
    name: 'Service Health Check',
    description: 'Comprehensive health check for common services — web server, database, and system services.',
    category: 'general',
    severity: 'info',
    builtin: true,
    platforms: ['linux', 'darwin'],
    tags: ['service', 'health', 'nginx', 'systemd'],
    estimatedMinutes: 5,
    steps: [
      { order: 1, title: 'List failed services', command: 'systemctl list-units --state=failed 2>/dev/null', description: 'Any systemd services in failed state.', risk: 'safe' },
      { order: 2, title: 'Check listening ports', command: 'sudo ss -ltnp | head -20', description: 'What services are listening on which ports.', risk: 'safe' },
      { order: 3, title: 'Test localhost HTTP', command: 'curl -sI http://localhost 2>/dev/null | head -10 || echo "No HTTP on localhost"', description: 'Quick check if a web server is responding.', risk: 'safe' },
      { order: 4, title: 'Check uptime and recent reboots', command: 'uptime && last reboot | head -5', description: 'System uptime and recent reboot history.', risk: 'safe' },
      { order: 5, title: 'Recent error logs', command: 'sudo journalctl -p err -n 20 --no-pager 2>/dev/null', description: 'Recent error-level log entries across all services.', risk: 'safe' },
    ],
  },
  {
    id: 'rb-docker-cleanup',
    name: 'Docker Cleanup',
    description: 'Clean up Docker resources — unused images, stopped containers, dangling volumes.',
    category: 'general',
    severity: 'info',
    builtin: true,
    platforms: ['linux', 'darwin'],
    tags: ['docker', 'containers', 'cleanup'],
    estimatedMinutes: 5,
    steps: [
      { order: 1, title: 'Docker disk usage', command: 'docker system df 2>/dev/null || echo "Docker not available"', description: 'Overview of space used by images, containers, and volumes.', risk: 'safe' },
      { order: 2, title: 'List all containers', command: 'docker ps -a --format "table {{.Names}}\\t{{.Status}}\\t{{.Size}}" 2>/dev/null | head -20', description: 'All containers including stopped ones.', risk: 'safe' },
      { order: 3, title: 'Dangling images', command: 'docker images -f "dangling=true" 2>/dev/null', description: 'Images not tagged or referenced by any container.', risk: 'safe' },
      { order: 4, title: 'Remove stopped containers', command: 'docker container prune -f 2>/dev/null && echo "Stopped containers removed"', description: 'Remove all stopped containers.', risk: 'caution' },
      { order: 5, title: 'Remove dangling images', command: 'docker image prune -f 2>/dev/null && echo "Dangling images removed"', description: 'Remove unreferenced images.', risk: 'caution' },
    ],
  },
  {
    id: 'rb-network-diag',
    name: 'Network Diagnostics',
    description: 'Troubleshoot network connectivity issues — DNS, routing, active connections, and firewall rules.',
    category: 'network',
    severity: 'warning',
    builtin: true,
    platforms: ['linux', 'darwin'],
    tags: ['network', 'dns', 'firewall', 'connectivity'],
    estimatedMinutes: 5,
    steps: [
      { order: 1, title: 'DNS resolution', command: 'dig google.com +short 2>/dev/null || nslookup google.com 2>/dev/null', description: 'Test if DNS is resolving correctly.', risk: 'safe' },
      { order: 2, title: 'External connectivity', command: 'ping -c 4 8.8.8.8', description: 'Test basic internet connectivity.', risk: 'safe' },
      { order: 3, title: 'Active connections', command: 'ss -s && echo "---" && ss -tnp | head -20', description: 'Socket statistics and top active connections.', risk: 'safe' },
      { order: 4, title: 'Routing table', command: 'ip route show 2>/dev/null || route -n 2>/dev/null', description: 'Current routing configuration.', risk: 'safe' },
      { order: 5, title: 'Firewall rules', command: 'sudo iptables -L -n --line-numbers 2>/dev/null | head -30 || sudo ufw status 2>/dev/null', description: 'Active firewall rules.', risk: 'safe' },
    ],
  },
  {
    id: 'rb-log-analysis',
    name: 'Log Analysis & Rotation',
    description: 'Analyze log files for errors, check log sizes, and verify log rotation is working.',
    category: 'general',
    severity: 'info',
    builtin: true,
    platforms: ['linux', 'darwin'],
    tags: ['logs', 'rotation', 'analysis', 'errors'],
    estimatedMinutes: 5,
    steps: [
      { order: 1, title: 'Log directory sizes', command: 'du -sh /var/log/* 2>/dev/null | sort -rh | head -15', description: 'Size of each log file and directory.', risk: 'safe' },
      { order: 2, title: 'Recent errors in syslog', command: 'sudo tail -100 /var/log/syslog 2>/dev/null | grep -iE "error|critical|fatal|panic" | tail -20', description: 'Error-level messages from syslog.', risk: 'safe' },
      { order: 3, title: 'Auth failures', command: 'sudo grep -i "failed\\|invalid\\|denied" /var/log/auth.log 2>/dev/null | tail -15', description: 'Recent authentication failures — possible intrusion attempts.', risk: 'safe' },
      { order: 4, title: 'Logrotate status', command: 'cat /var/lib/logrotate/status 2>/dev/null | tail -20 || echo "No logrotate status file found"', description: 'When each log was last rotated.', risk: 'safe' },
    ],
  },
  {
    id: 'rb-security-audit',
    name: 'Quick Security Audit',
    description: 'Basic security checks — open ports, recent logins, pending updates, and suspicious processes.',
    category: 'security',
    severity: 'warning',
    builtin: true,
    platforms: ['linux', 'darwin'],
    tags: ['security', 'audit', 'ssh', 'updates'],
    estimatedMinutes: 8,
    steps: [
      { order: 1, title: 'Open ports', command: 'sudo ss -ltnp', description: 'All listening TCP ports and their processes.', risk: 'safe' },
      { order: 2, title: 'Recent logins', command: 'last -20', description: 'Last 20 login sessions.', risk: 'safe' },
      { order: 3, title: 'Failed login attempts', command: 'sudo grep "Failed password" /var/log/auth.log 2>/dev/null | tail -15 || sudo journalctl _COMM=sshd | grep "Failed" | tail -15', description: 'Brute force attempts or unauthorized access.', risk: 'safe' },
      { order: 4, title: 'Pending security updates', command: 'apt list --upgradable 2>/dev/null | head -20 || yum check-update --security 2>/dev/null | head -20', description: 'Available security patches.', risk: 'safe' },
      { order: 5, title: 'SUID binaries', command: 'find / -perm -4000 -type f 2>/dev/null | head -20', description: 'Files with SUID bit — potential privilege escalation vectors.', risk: 'safe' },
    ],
  },
  {
    id: 'rb-win-disk-recovery',
    name: 'Windows Disk Recovery',
    description: 'Recover disk space on a Windows server. Checks disk usage and cleans temp files.',
    category: 'storage',
    severity: 'critical',
    builtin: true,
    platforms: ['win32'],
    tags: ['disk', 'storage', 'cleanup', 'windows'],
    estimatedMinutes: 5,
    steps: [
      { order: 1, title: 'Check disk usage', command: 'Get-Volume | Where-Object DriveType -eq Fixed', description: 'See which drives are full.', risk: 'safe' },
      { order: 2, title: 'Clean temp files', command: 'Remove-Item -Path $env:TEMP\\* -Recurse -Force -ErrorAction SilentlyContinue; Write-Output "Temp files cleaned"', description: 'Clean user temp folder.', risk: 'safe' },
      { order: 3, title: 'Find largest files', command: 'Get-ChildItem -Path C:\\ -File -Recurse -ErrorAction SilentlyContinue | Sort-Object Length -Descending | Select-Object -First 10 Name, Length', description: 'Identify top space consumers.', risk: 'safe' },
    ],
  },
  {
    id: 'rb-win-service-health',
    name: 'Windows Service Health',
    description: 'Check Windows services and processes.',
    category: 'general',
    severity: 'warning',
    builtin: true,
    platforms: ['win32'],
    tags: ['service', 'windows'],
    estimatedMinutes: 3,
    steps: [
      { order: 1, title: 'Stopped automatic services', command: 'Get-Service | Where-Object {$_.StartType -eq "Automatic" -and $_.Status -ne "Running"}', description: 'Services that should be running but are not.', risk: 'safe' },
      { order: 2, title: 'High CPU processes', command: 'Get-Process | Sort-Object CPU -Descending | Select-Object -First 10 ProcessName, CPU, WS', description: 'Top CPU consumers.', risk: 'safe' },
      { order: 3, title: 'Recent system errors', command: 'Get-WinEvent -MaxEvents 20 -LogName System -ErrorAction SilentlyContinue | Where-Object LevelDisplayName -eq "Error" | Select-Object TimeCreated, Message', description: 'System event log errors.', risk: 'safe' },
    ],
  }
];
